/**
 * Local helper when developing under apps/web.
 * On Vercel, scripts/prepare-vercel.js (repo root) is used instead.
 */
const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '..', 'public', 'js');
const outFile = path.join(outDir, 'runtime-config.js');

const apiUrl = (
  process.env.CUPS_API_URL ||
  process.env.NEXT_PUBLIC_API_URL ||
  '/api/v1'
).replace(/\/$/, '');

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(
  outFile,
  [
    '/* Generated by apps/web/scripts/prepare-vercel.js */',
    `window.CUPS_API_URL = ${JSON.stringify(apiUrl)};`,
    '',
  ].join('\n'),
  'utf8',
);

console.log(`runtime-config.js CUPS_API_URL=${apiUrl}`);
