/**
 * Writes public/js/runtime-config.js at build time.
 * Set CUPS_API_URL or NEXT_PUBLIC_API_URL in Vercel env.
 */
const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '..', 'public', 'js');
const outFile = path.join(outDir, 'runtime-config.js');

const apiUrl = (
  process.env.CUPS_API_URL ||
  process.env.NEXT_PUBLIC_API_URL ||
  ''
).replace(/\/$/, '');

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(
  outFile,
  [
    '/* Generated by apps/web/scripts/prepare-vercel.js */',
    `window.CUPS_API_URL = ${JSON.stringify(apiUrl)};`,
    '',
  ].join('\n'),
  'utf8',
);

console.log(
  apiUrl
    ? `Vercel runtime config: CUPS_API_URL=${apiUrl}`
    : 'Vercel runtime config: CUPS_API_URL empty (set it in Vercel env for live API)',
);
