/**
 * Prepare static site + API base URL for Vercel.
 * Defaults to same-origin /api/v1 so the Vercel serverless API works.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const srcPublic = path.join(root, 'apps', 'web', 'public');
const outPublic = path.join(root, 'public');

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(from, to);
    else fs.copyFileSync(from, to);
  }
}

copyDir(srcPublic, outPublic);

const apiUrl = (
  process.env.CUPS_API_URL ||
  process.env.NEXT_PUBLIC_API_URL ||
  '/api/v1'
).replace(/\/$/, '');

const configFile = path.join(outPublic, 'js', 'runtime-config.js');
fs.mkdirSync(path.dirname(configFile), { recursive: true });
fs.writeFileSync(
  configFile,
  [
    '/* Generated by scripts/prepare-vercel.js */',
    `window.CUPS_API_URL = ${JSON.stringify(apiUrl)};`,
    '',
  ].join('\n'),
  'utf8',
);

console.log(`Vercel static copied to /public; CUPS_API_URL=${apiUrl}`);
